name: Publish documentation

on:
  push:
    branches:
      - generate-api-docs
      - master
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fetch all git branches
        run: git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm install --engine-strict --no-lockfile
      - run: npm run docs:build
      - uses: docker://malept/gha-gh-pages:1.0.0
        with:
          docsPath: typedoc
          showUnderscoreFiles: true
          versionDocs: true
        env:
          DOCS_SSH_DEPLOY_KEY: ${{ secrets.DOCS_SSH_DEPLOY_KEY }}
