name: Publish documentation

on:
  push:
    branches:
      - generate-api-docs
      - master
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions@setup-node@v1
        with:
          node-version: 12.x
      - run: npm install --engine-strict --no-lockfile
      - run: test/ci/publish_docs.sh
