name: Symlink Test

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
        with:
          repository: electron/electron-quick-start
          ref: refs/heads/master
          path: electron-quick-start
      - name: Use Node.js 8.x
        uses: actions/setup-node@v1
        with:
          node-version: 8.x
      - name: Install
        run: |
          cd ../electron-quick-start
          npm install
      - name: Install Electron Packager
        run: |
          cd ../electron-quick-start
          npm install --save-dev electron-packager@electron/electron-packager
      - name: Package
        run: |
          cd ../electron-quick-start
          node_modules/.bin/electron-packager . --platform=darwin
      - uses: actions/upload-artifact@v1
        with:
          name: app
          path: ../electron-quick-start/electron-quick-start-darwin-x64
  test:
    needs: build
    runs-on: macOS-latest
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: app
          path: electron-quick-start-darwin-x64
      - name: Check symlink
        run: |
          find electron-quick-start.app
